# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

pms.morshoo.com	FALSE	/	FALSE	0	zentaosid	e4edfcbeoak8g43nlidko5k6e7
pms.morshoo.com	FALSE	/	FALSE	1529939356	lang	zh-cn
pms.morshoo.com	FALSE	/	FALSE	1529939356	device	desktop
pms.morshoo.com	FALSE	/	FALSE	1529939356	theme	default
